baseURL = 'https://yangzongyi.cn/'
languageCode = 'zh-cn'
title = '杨宗亿的个人博客'
theme = 'stack'

[params]
    mainSections = ["post"]

    [params.sidebar]
        subtitle = "通信工程 | Python | LLM"
        avatar = "/portrait.jpg" 
		description = "这里记录我从 0 到 1 的技术成长之路。"
    [params.article]
        toc = true
        readingTime = true
        wordCount = true

    # --- 社交链接：注意这里必须是双括号 [[...]] ---
    [[params.social]]
        name = "GitHub"
        icon = "github"
        url = "https://github.com/Yangzy963"

    [[params.social]]
        name = "E-mail"
        icon = "mail"
        url = "mailto:yourname@email.com"

    # --- 小组件配置 ---
    [params.widgets]
        enabled = ["search", "archives", "tag_cloud"]

        [params.widgets.search]
            title = "搜索"

        [params.widgets.archives]
            title = "历史归档"
            limit = 5

        [params.widgets.tag_cloud]
            title = "我的标签"

# --- 菜单配置：必须放在 params 块之外 ---
[menu]
    [[menu.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 1
        params = { icon = "home" }

    [[menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/post/"
        weight = 2
        params = { icon = "pen-tool" }
		
# hugo.toml 配置示例

# 1. 开启 Emoji 表情支持
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # 2. 允许在 Markdown 中直接写 HTML (解决 <u>下划线 不显示的问题)
      unsafe = true